#!/bin/sh
set -e
apt-get update
apt-get install -y \
  autoconf \
  automake \
  build-essential \
  gcc \
  gdb \
  git \
  go-md2man \
  golang-go \
  iptables \
  libapparmor-dev \
  libassuan-dev \
  libbtrfs-dev \
  libc6-dev \
  libcap-dev \
  libdevmapper-dev \
  libglib2.0-dev \
  libgpg-error-dev \
  libgpgme-dev \
  libprotobuf-dev \
  libseccomp-dev \
  libselinux1-dev \
  libssl-dev \
  libsystemd-dev \
  libtool \
  libyajl-dev \
  nano \
  openssl \
  pkg-config \
  python3 \
  strace \
  uidmap \
  vim \
